<?php 
return [
'cnf_appname' 			=> 'Help Desk',
'cnf_appdesc' 			=> 'Help Desk',
'cnf_comname' 			=> 'Help Desk',
'cnf_email' 			=> 'helpdeskogti@gmail.com',
'cnf_metakey' 			=> '',
'cnf_metadesc' 		=> '',
'cnf_group' 			=> '3',
'cnf_activation' 		=> 'manual',
'cnf_multilang' 		=> '1',
'cnf_lang' 			=> 'en',
'cnf_regist' 			=> 'false',
'cnf_front' 			=> 'false',
'cnf_recaptcha' 		=> 'false',
'cnf_theme' 			=> 'bootstrap',
'cnf_recaptchapublickey' => '',
'cnf_recaptchaprivatekey' => '',
'cnf_mode' 			=> 'production',
'cnf_logo' 			=> 'backend-logo.png',
'cnf_allowip' 			=> '',
'cnf_restrictip' 		=> '192.116.134 , 194.111.606.21 ',
'cnf_mail' 			=> 'swift',
'cnf_date' 			=> 'Y-m-d',
];
